/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CirclesNewRouteImport } from './routes/circles.new'
import { Route as CirclesCircleNameRouteImport } from './routes/circles.$circleName'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesNewRoute = CirclesNewRouteImport.update({
  id: '/circles/new',
  path: '/circles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesCircleNameRoute = CirclesCircleNameRouteImport.update({
  id: '/circles/$circleName',
  path: '/circles/$circleName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/circles/$circleName': typeof CirclesCircleNameRoute
  '/circles/new': typeof CirclesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/circles/$circleName': typeof CirclesCircleNameRoute
  '/circles/new': typeof CirclesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/circles/$circleName': typeof CirclesCircleNameRoute
  '/circles/new': typeof CirclesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email'
    | '/friends'
    | '/login'
    | '/profile'
    | '/circles/$circleName'
    | '/circles/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/friends'
    | '/login'
    | '/profile'
    | '/circles/$circleName'
    | '/circles/new'
  id:
    | '__root__'
    | '/'
    | '/confirm-email'
    | '/friends'
    | '/login'
    | '/profile'
    | '/circles/$circleName'
    | '/circles/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  FriendsRoute: typeof FriendsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  CirclesCircleNameRoute: typeof CirclesCircleNameRoute
  CirclesNewRoute: typeof CirclesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/new': {
      id: '/circles/new'
      path: '/circles/new'
      fullPath: '/circles/new'
      preLoaderRoute: typeof CirclesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/$circleName': {
      id: '/circles/$circleName'
      path: '/circles/$circleName'
      fullPath: '/circles/$circleName'
      preLoaderRoute: typeof CirclesCircleNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  FriendsRoute: FriendsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  CirclesCircleNameRoute: CirclesCircleNameRoute,
  CirclesNewRoute: CirclesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
